#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# $Id: palabre-script,v 1.3 2006/08/08 10:58:56 lightdruid Exp $
#

import os, sys

if hasattr(sys, 'frozen'):
    sys.path.append(os.path.abspath(os.path.dirname(sys.argv[0])))

if __name__ == '__main__':
    
    if not os.path.exists('/etc/palabre.conf'):
        sys.exit("'/etc/palabre.conf' is missing.")
    
    if len(sys.argv) != 2 or sys.argv[1] not in ['start', 'stop', 'restart', 'status']:
        sys.exit("Usage: %s start|stop|restart|status" % sys.argv[0])

    from palabre import palabreDaemon
    daemon = palabreDaemon.palabreDaemon()
    daemon.control(sys.argv[1])

# ---
