.\" -*-nroff-*-
.\"
.\" $Id: nanoicqrc.5,v 1.1 2006/02/23 15:37:01 lightdruid Exp $
.\"

.TH NanoICQ "5" "February 2006" 
.SH NAME
nanoicqrc - NanoICQ configuration file

.SH SYNOPSIS
\fBnanoicq\fR [ \fIoptions\fR ]

.SH DESCRIPTION

.SH SEE ALSO
\fBnanoicq\fR(1), \fBoptions\fR(n)

.PP
\fB/usr/share/doc/nanoicq/README.gz\fR

.PP
\fB/usr/share/doc/nanoicq/examples/nanoicqrc.example.gz\fR

.PP
NanoICQ home page (\fBhttp://nanoicq.berlios.de/\fR)

.SH AUTHORS
NanoICQ was written by Andrey Sidorenko <sidorenko@gmail.com>.

.PP

This is free documentation; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
